repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.252'
    #ignore F401 (F401 is unused import)
    additional_dependencies: [ruff==0.0.252]
    hooks:
    -   id: ruff
        args: [--ignore, F401, --fix]
